version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: flaskapp
      POSTGRES_PASSWORD: qwerty123
      POSTGRES_DB: rad
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    command: flask run --host=0.0.0.0
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://flaskapp:qwerty123@db:5432/rad

volumes:
  postgres_data: